
# Netlify Configuration for Product Color Viewer

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Scheduled Functions Configuration
# Keep-alive function runs on Mondays, Wednesdays, and Fridays at 9:00 AM UTC
# to prevent Supabase free tier database from pausing due to inactivity

[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

[functions.keep-alive]
  schedule = "0 9 * * 1,3,5"  # Every Monday, Wednesday, Friday at 9:00 AM UTC
  # Equivalent cron schedule in text:
  # "At 09:00 AM UTC, on Monday, Wednesday, and Friday"

