
# Netlify Configuration for Product Color Viewer

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Functions Configuration
# Scheduled Functions will run automatically on specified schedule
[functions]
  directory = "netlify/functions"
  
# Note: Scheduled functions configuration in netlify.toml is being deprecated
# Configure the schedule directly in the Netlify dashboard for the keep-alive function
# Schedule: "0 9 * * 1,3,5" (Every Monday, Wednesday, Friday at 9:00 AM UTC)

