// IMPORTANT SUPABASE SETUP INSTRUCTIONS:
// 1. Create a new project at https://supabase.com/.
// 2. Go to the "SQL Editor" tab in your Supabase project dashboard.
// 3. Run the following SQL queries to create the necessary tables:

/*
-- Create the articles table
CREATE TABLE public.articles (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  article_number text NOT NULL,
  name text NULL,
  CONSTRAINT articles_pkey PRIMARY KEY (id),
  CONSTRAINT articles_article_number_key UNIQUE (article_number)
);

-- Create the colors table
CREATE TABLE public.colors (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  article_id bigint NOT NULL,
  image_url text NOT NULL,
  storage_path text NOT NULL,
  CONSTRAINT colors_pkey PRIMARY KEY (id),
  CONSTRAINT colors_article_id_fkey FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE
);

-- Create a storage bucket for product color images
-- Go to the "Storage" tab in your Supabase project dashboard.
-- Click "New bucket", name it "product-colors", and make it a public bucket.
-- Set up Row Level Security (RLS) policies for your tables in the "Authentication" -> "Policies" tab
-- For a quick start, you can enable read access for everyone and restrict write access.
-- Example RLS Policy for public read access on 'articles':
-- Target Roles: anon, authenticated
-- USING expression: true
*/

// 4. Set up your credentials using environment variables.
// Make sure to create a .env.local file with your Supabase credentials:
// VITE_SUPABASE_URL=your_supabase_url
// VITE_SUPABASE_ANON_KEY=your_anon_key

// This code assumes the Supabase client is available on the window object
// because it's loaded from a CDN in index.html.
// @ts-ignore
const { createClient } = window.supabase;

// Get credentials from environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
    throw new Error("Supabase URL and Anon Key must be provided in environment variables. Please check your .env.local file.");
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
